sonar.projectKey=esef-data-fetcher
sonar.projectName=esef-data-fetcher

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.exclusions=setup.py,src/config.py,src/entity_registry.py
